### ISSUE TITLE
Unable to delete reviews

### ISSUE THREAD

**Issue by contactandy** [convus/convus_reviews#29]
If I edit a review and select `delete_review` as in this screenshot: 
![Screenshot 2023-03-23 210139](https://user-images.githubusercontent.com/124109523/227398124-aaec9900-d975-4190-afde-e284421f10ab.png)
I get the following error message:
![Screenshot 2023-03-23 210041](https://user-images.githubusercontent.com/124109523/227398206-f0d2e5d4-2c35-41b1-9b1d-5207da1cee83.png)

**Comment by contactandy** [comment]
Annnd it was because I had NoScript on. My bad.

**Comment by sethherr** [comment]
This specific issue will be fixed by #30 - but other things, like localized date display, won't be fixed.

I recommend keeping NoScript off for convus 😉
